# Generated by Django 3.2.5 on 2021-08-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210810_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='Gender_pet',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=' ', max_length=100),
        ),
    ]
