# Generated by Django 3.2.5 on 2021-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_takeappointment_gender_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='institute_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='qualification_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='Gender_pet',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='phone_number',
            field=models.CharField(max_length=120),
        ),
    ]
